#!/usr/bin/env bash

if pycodestyle api/v1/app.py; then
    echo "Successfully ran pycodestyle on api/v1/app.py"
else
    echo "Error running pycodestyle on api/v1/app.py"
fi

if pycodestyle api/v1/auth/auth.py; then
    echo "Successfully ran pycodestyle on api/v1/auth/auth.py"
else
    echo "Error running pycodestyle on api/v1/auth/auth.py"
fi

if pycodestyle api/v1/auth/basic_auth.py; then
    echo "Successfully ran pycodestyle on api/v1/auth/basic_auth.py"
else
    echo "Error running pycodestyle on api/v1/auth/basic_auth.py"
fi

if pycodestyle api/v1/auth/session_auth.py; then
    echo "Successfully ran pycodestyle on api/v1/auth/session_auth.py"
else
    echo "Error running pycodestyle on api/v1/auth/session_auth.py"
fi

if pycodestyle api/v1/views/index.py; then
    echo "Successfully ran pycodestyle on api/v1/views/index.py"
else
    echo "Error running pycodestyle on api/v1/views/index.py"
fi

if pycodestyle api/v1/views/session_auth.py; then
    echo "Successfully ran pycodestyle on api/v1/views/session_auth.py"
else
    echo "Error running pycodestyle on api/v1/views/session_auth.py"
fi

if pycodestyle api/v1/views/users.py; then
    echo "Successfully ran pycodestyle on api/v1/views/users.py"
else
    echo "Error running pycodestyle on api/v1/views/users.py"
fi
