#!/usr/bin/env bash

if pycodestyle api/v1/app.py; then
    echo "Successfully ran pycodestyle on api/v1/app.py"
else
    echo "Error running pycodestyle on api/v1/app.py"
fi

if pycodestyle api/v1/auth/*auth.py; then
    echo "Successfully ran pycodestyle on api/v1/auth/*auth.py"
else
    echo "Error running pycodestyle on api/v1/auth/*auth.py"
fi

if pycodestyle api/v1/views/{index.py,session_auth.py,users.py}; then
    echo "Successfully ran pycodestyle on api/v1/views/{index.py,session_auth.py,users.py}"
else
    echo "Error running pycodestyle on api/v1/views/{index.py,session_auth.py,users.py}"
fi

# pycodestyle api/v1/views/session_auth.py
# pycodestyle api/v1/views/index.py
# pycodestyle api/v1/views/users.py
